#!/usr/bin/env bash


# Update files
sudo apt update && sudo upgrade -y

# Install basic packages
sudo apt install -y wget curl nano git

# Loads .profile for bashrc too
echo "# Loads .profile
if [ -f ~/.profile ]; then
    . ~/.profile
fi" >> ~/.bashrc

# Dotfiles repository
if ! command -v config &> /dev/null
then
  git clone --bare git@github.com:arthurfiorette/dotfiles.git $HOME/.dotfiles || true
  alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
  config config --local status.showUntrackedFiles no
  config fetch
  config checkout main origin/main
fi

# Sets up ZSH
if ! command -v zsh &> /dev/null
then
  sudo apt install -y zsh-autosuggestions zsh-syntax-highlighting zsh fonts-powerline
  sudo chsh -s $(which zsh) # default shell
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" #oh-my-zsh

  # ZSH plugins
  git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions # autossugestions
  git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git $ZSH_CUSTOM/plugins/fast-syntax-highlighting # syntax highlight
  git clone https://github.com/marlonrichert/zsh-autocomplete.git $ZSH_CUSTOM/plugins/zsh-autocomplete --depth=1 # autocomplete

  # ZSH theme
  curl -sS https://starship.rs/install.sh | sh
fi

# Sets up docker
if ! command -v docker &> /dev/null
then
  sudo apt install -y ca-certificates curl gnupg
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  sudo chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo apt update
  sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  sudo usermod -aG docker $(whoami)
fi

# Sets up Node & NVM
if ! command -v node &> /dev/null
then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  nvm alias default node # defaults version
  npm i -g pnpm typescript npm # updates default packages
fi

# Sets up rust
if ! command -v cargo &> /dev/null
then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi